// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3KjJCHQ0ymv2iAhqaQ5bjOlu4JB33rRw',
    appId: '1:730548367609:web:c1d7a5eaef741caadeb228',
    messagingSenderId: '730548367609',
    projectId: 'to-do-list-d59ed',
    authDomain: 'to-do-list-d59ed.firebaseapp.com',
    storageBucket: 'to-do-list-d59ed.appspot.com',
    measurementId: 'G-T2C86PB4VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBydxJ_0VflSLYLYMJte3dZSF2FUaraxJ8',
    appId: '1:730548367609:android:f188a87c3af9a582deb228',
    messagingSenderId: '730548367609',
    projectId: 'to-do-list-d59ed',
    storageBucket: 'to-do-list-d59ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTB6YM1Bo0D2r1g-9CX9M4Fzi6gHpDGvE',
    appId: '1:730548367609:ios:3809f1f8c5b2f770deb228',
    messagingSenderId: '730548367609',
    projectId: 'to-do-list-d59ed',
    storageBucket: 'to-do-list-d59ed.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTB6YM1Bo0D2r1g-9CX9M4Fzi6gHpDGvE',
    appId: '1:730548367609:ios:d0bcbdcaf5aa878edeb228',
    messagingSenderId: '730548367609',
    projectId: 'to-do-list-d59ed',
    storageBucket: 'to-do-list-d59ed.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
